routes/admin.php
<?php

/**
 * Admin Routes
 *
 * prefix : /admin
 * namespace : Web\
 */

Route::get('/', function () {
    return redirect('/admin/login');
});

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout');

// Register Routes...
Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('auth.change_password');
Route::post('/register', 'Auth\RegisterController@register')->name('auth.change_password');

// Password Reset Routes
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Change Password Routes...
Route::get('/change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('/change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');


Route::group(['middleware' => ['auth:admin']], function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    });

    Route::get('/members', 'Member\Index@index');

    Route::get('/users', 'UserController@index');
    Route::get('/users/create', 'UserController@create');
    Route::post('/users', 'UserController@store');
    Route::get('/users/{id}/edit', 'UserController@edit');
    Route::put('/users/{id}', 'UserController@update');
    Route::delete('/users/{id}', 'UserController@delete');

    Route::get('/richmenus', 'Richmenu\Index');
    Route::get('/richmenus/create', 'Richmenu\Create');
});

routes/web.php
<?php

/**
 * Web Routes
 *
 * namespace : Web\
 */

Route::get('/', function () {
    return view('welcome');
});

Route::get('/member/line/login', 'Auth\LoginController@lineLogin'); // Line Login redirect 回頁的統一路口

Route::group(['middleware' => ['auth.line', 'checkMemberBind']], function () {
    Route::get('/member/agreement', 'MemberController@showAgreement');
    Route::get('/member/inputdata', 'MemberController@showInputData');
    Route::post('/member/checkphone', 'MemberController@showCheckPhone');
    Route::post('/member/sendsmsotp', 'MemberController@sendSmsOtp');
    Route::post('/member/verifysmsotp', 'MemberController@verifySmsOtp');
    Route::get('/member/success', 'MemberController@showSuccess');
});

app/Models/Member.php
<?php

namespace App\Models;

use App\Models\MemberLine;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;

class Member extends Authenticatable
{
    use Notifiable;

    protected $table = 'members';
    protected $primaryKey = 'id';

    protected $fillable = [
        'name',
        'card_no',
        'cellphone',
        'birthday',
        'address',
        'email',
        'password'
    ];
    protected $hidden = ['password'];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($input)
    {
        if ($input) {
            $this->attributes['password'] = Hash::needsRehash($input) ? Hash::make($input) : $input;
        }
    }

    public function line()
    {
        return $this->hasOne(MemberLine::class, 'members_id', 'id');
    }

    public function getProfileInfoAttribute()
    {
        $data = $this->only(['name', 'email', 'cellphone', 'birthday', 'address']);

        $data = array_filter($data, function ($value) {
            return !is_null($value) && $value !== '';
        });

        return implode("<br>", $data);
    }
}

app/Http/Controllers/Admin/Member/Index.php
<?php

namespace App\Http\Controllers\Admin\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Member;

class Index extends Controller
{
    public function index(Request $request)
    {
        $query = Member::orderBy('id', 'desc');

        if (request('name')) {
            $query->where('name', 'like', '%'.request('name').'%');
        }
        if (request('email')) {
            $query->where('email', 'like', '%'.request('email').'%');
        }

        $request->session()->put('LIST_URL', url()->full());

        return view('admin.members.index', [
            'members' => $query->paginate(config('adminlte.pagesize'))
        ]);
    }
}

app/Http/Controllers/Web/MemberController.php
<?php

namespace App\Http\Controllers\Web;

use App\Models\Member;
use Illuminate\Support\Str;
use App\Services\SmsService;
use Illuminate\Http\Request;
use App\Services\ErrorService;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redis;
use Illuminate\Support\Facades\Session;

class MemberController extends Controller
{
    public function __construct()
    {
    }

    public function showAgreement(Request $request)
    {
        return view('member.agreement');
    }

    public function showInputData(Request $request)
    {
        return view('member.inputdata');
    }

    public function showCheckPhone(Request $request)
    {
        Session::put('userdata', $request->all());

        $otp_ttl = (new SmsService)->getOtpTtl($request->cellphone);

        return view('member.checkphone', [
            'otp_ttl' => $otp_ttl,
            'cellphone' => $request->cellphone
        ]);
    }

    public function sendSmsOtp(Request $request)
    {
        (new SmsService)->createOtp($request->cellphone);
    }

    public function verifySmsOtp(Request $request)
    {
        try {
            (new SmsService)->verifyOtp($request->cellphone, $request->otp_number);

            // 資料填入
            $userdata = Session::pull('userdata');
            $member = Auth::guard('web')->user();
            $member->name = $userdata['name'];
            $member->cellphone = $userdata['cellphone'];
            $member->birthday = $userdata['birthday'];
            $member->card_no = Str::random(10);
            $member->save();
        } catch (\Exception $e) {
            return response()->json([
                'code' => $e->getCode(),
                'msg' => $e->getMessage(),
            ], 400);
        }

        return response()->json([
            'msg' => 'success'
        ], 200);
    }

    public function showSuccess(Request $request)
    {
        return view('member.success');
    }
}

resources/views/admin/members/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('css')
<style>
    .line_block_img {
        width: 80px;
        text-align: center;
    }

    .line_block_img img {
        width: 60px;
        height: 60px;
        border-radius: 50%;
    }

    .line_block_uid {
        color: #999;
    }
</style>
@stop

@section('content_header')
    <h1>會員管理</h1>
@stop

@section('content')

{{-- Search Form --}}
<div class="card card-default">
    <form id="searchForm" method="GET">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <label>Name</label>
                <input type="text" name="name" class="form-control" value="{{ request('name') }}" autofocus>
            </div>
            <div class="col-md-3">
                <label>Email</label>
                <input type="text" name="email" class="form-control" value="{{ request('email') }}">
            </div>
        </div>
    </div>
    </form>
    <div class="card-footer">
        <button id="search" class="btn btn-sm btn-info"><i class="fa fa-search"></i> 搜尋</button>
        <button id="reset" class="btn btn-sm btn-warning"><i class="fa fa-eraser"></i> 清除</button>
    </div>
</div>

{{-- DataTable --}}
<div class="card card-default">
    <div class="card-header">
        <a class="btn btn-sm btn-success" href="users/create">
            <i class="fa fa-plus"></i> 新增
        </a>
    </div>

    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 5%">#</th>
                    <th style="width: 15%">Profile Info</th>
                    <th>LINE</th>
                    <th style="width: 20%">建立時間</th>
                    <th style="width: 15%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($members as $member)
                    <tr>
                        <td>{{ $member->id }}</td>
                        <td>
                            {!! $member->profile_info !!}
                        </td>
                        <td>
                            <div class="row">
                                <div class="line_block_img">
                                    <img src="{{ $member->line->pictureUrl ?? '' }}">
                                </div>
                                <div class="line_block_info">
                                    {{ $member->line->displayname ?? '' }}
                                    <br>
                                    <span class="line_block_uid">{{ $member->line->uid ?? '' }}</span>
                                </div>
                            </div>
                        </td>
                        <td>{{ $member->created_at }}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="members/{{ $member->id ?? ''}}/edit">
                                編輯
                            </a>

                            <form method="POST" action="members/{{ $member->id ?? '' }}" style="display: inline-block;"
                                onsubmit="return confirm('確認刪除？')">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button class="btn btn-sm btn-danger" type="submit">
                                    刪除
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="card-footer">
        {{ $members->appends(request()->except('page'))->links() }}
    </div>
</div>

@stop

@section('css')

@stop

@section('js')
<script>
    function init() {
        const form = $('#searchForm');
        common.initForm(form);

        $('#search').click(function () {
            form.submit();
        });
        $('#reset').click(function () {
            common.resetForm(form);
        });

        form.find(':input').keypress(function (event) {
            if (event.keyCode == 13) {
                form.submit();
            }
        });
    }

    init();
</script>
@stop